name: Build & Publish

on:
  push:
    tags: [ '*' ]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Compile and Test Library
        run: ./gradlew build

  publish:
    name: Publish to Sonatype & GitHub Packages
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Extract Tag Version
        run: |
          REF_NAME="${{ github.ref_name }}"
          VERSION="${REF_NAME#v}"
          if [ -n "$VERSION" ]; then
            echo "PUBLISH_VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Publish Bundle to registries
        run: |
          if [ -n "$PUBLISH_VERSION" ]; then
            ./gradlew publish -PPUBLISH_VERSION=$PUBLISH_VERSION
          else
            ./gradlew publish
          fi
        env:
          ORG_GRADLE_PROJECT_PUBLISH_REPO_URL: "https://central.sonatype.com/api/v1/publisher/deployments"
          ORG_GRADLE_PROJECT_PUBLISH_REPO_USERNAME: ${{ secrets.PUBLISH_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_PUBLISH_REPO_PASSWORD: ${{ secrets.PUBLISH_REPO_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_GITHUB_USERNAME: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
